x-environment: &environment
  POSTGRES_USER: elysia
  POSTGRES_PASSWORD: elysia
  POSTGRES_DB: elysia-todo

services:
  postgres:
    image: postgres:13
    container_name: elysia-todo-postgres
    # Volume init.sql replaced with TypeORM
    environment:
      <<: *environment
    ports:
      - "5435:5432"