x-environment: &environment
  POSTGRES_USER: elysia
  POSTGRES_PASSWORD: elysia
  POSTGRES_DB: elysia-todo

services:
  postgres:
    image: postgres:13
    container_name: elysia-todo-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      <<: *environment
    ports:
      - "5435:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elysia-todo-api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      <<: *environment
    depends_on:
      - postgres