x-environment: &environment
  POSTGRES_USER: elysia
  POSTGRES_PASSWORD: elysia
  POSTGRES_DB: elysia-todo

services:
  postgres:
    image: postgres:13
    container_name: elysia-todo-postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Setup a volume to save the data
    environment:
      <<: *environment
    ports:
      - "5435:5432"